#!/usr/bin/env python3
"""Append Accessibility Notes + Design Decisions Explained to each style README."""
import glob, os

BLOCK = """
## 14 · Accessibility Notes
- Contrast targets: body 4.5:1, large text/UI 3:1 — verify every text/background pair in this style's palette.
- Focus states: {focus}.
- Motion: this style tempts toward {motion_risk}. Every animated surface needs a `prefers-reduced-motion` static fallback.
- Common a11y failure in this style: {a11y_trap}.

## 15 · Design Decisions Explained (why, not just what)
- **Why these fonts:** {font_why}
- **Why this radius:** {radius_why}
- **Why this density:** {density_why}
- **Signature move:** the ONE element that makes a page instantly recognizable as this style — use once per page, deliberately.
- **When to break the rules:** {break_rules}
"""

VARIANTS = {
 "01-minimalism": dict(focus="a 2px accent-colored ring, never just a color change", motion_risk="parallax and scroll reveals that add nothing to a quiet page", a11y_trap="light gray secondary text (#999 on white) fails 4.5:1 — keep secondary at #555 or darker", font_why="a neutral grotesk carries restraint without personality overload; the whitespace does the expressing — a display serif here would fight the quietness", radius_why="small radii (8-12px) signal precision; pill-everything reads consumer-app, sharp 0 can read harsh in B2B", density_why="low density is the point — but never below the information threshold: a page with one sentence is empty, not minimal", break_rules="allow ONE expressive element (oversized number, single accent illustration) when restraint starts reading as blandness — break the pattern deliberately, once"),
 "02-glassmorphism": dict(focus="a solid 2px ring — focus indicators get lost in blur and translucency", motion_risk="parallax blobs behind every glass surface — blur plus movement equals motion sickness and battery drain", a11y_trap="text over translucent glass over a vivid image fails contrast unpredictably — always give glass surfaces a solid fallback background", font_why="a clean geometric sans survives blur best; thin serifs dissolve into the frosted layer and become unreadable", radius_why="larger radii (16-20px) reinforce the soft pane metaphor; sharp corners make glass look like broken windows", density_why="2 glass surfaces per view max — more translucency stacks into visual noise; content density belongs on solid surfaces", break_rules="drop glass entirely for dense sections (tables, forms) — glass is for navigation, overlays and heroes, never for data"),
 "03-liquid-glass": dict(focus="high-contrast pill outlines; the fluid material eats thin focus rings", motion_risk="everything morphs and floats — continuous animation without reduced-motion fallback is the #1 failure", a11y_trap="liquid refraction distorts text near edges — keep text 16px+ with padding away from material boundaries", font_why="rounded-humanist sans matches the fluid material; rigid grotesks clash with the organic light behavior", radius_why="full pills (999px) echo the liquid metaphor — the material has no corners, neither should the chrome", density_why="consumer-light by design; this style collapses under dashboards — it is a marketing/navigation language", break_rules="swap liquid for solid panels in settings/forms — familiarity beats material consistency where users work"),
 "04-bento-grid": dict(focus="ring on the interactive tile only; tile borders must not all glow at once", motion_risk="every tile hovering/lifting simultaneously — stagger hover motion, animate one tile at a time", a11y_trap="low-contrast text on colored tiles (white on pastel accent) — tiles are surfaces, not backgrounds for failing contrast", font_why="a workhorse grotesk handles varied tile content; expressive display fonts per-tile fragment the grid into a ransom note", radius_why="one radius for all tiles — uniformity IS the bento promise; mixing radii destroys the modular metaphor", density_why="the style's superpower and its trap: high density needs ruthless tile hierarchy (one hero tile, supporting tiles quiet)", break_rules="one full-bleed break of the grid per page (a tile spanning edge-to-edge) adds drama without breaking the system"),
 "05-neo-brutalism": dict(focus="thick black 3px+ outline focus — it is already the aesthetic, keep it on every interactive element", motion_risk="bouncy spring easing everywhere — hard shadows should SNAP (150ms linear), not wobble", a11y_trap="yellow-on-white or neon-on-neon text; loud style still means 4.5:1 body contrast", font_why="ultra-bold grotesks (Archivo Black) are the voice — the style IS loud typography; light weights contradict the material", radius_why="0-4px radius only; rounded brutalism is just default UI with a border — the sharpness is semantic", density_why="high-contrast density works: big type, chunky blocks — but elements must align to a grid even when they look chaotic", break_rules="never soften it; if the brand can't take loudness, change style — half-brutalism is the definition of slop"),
 "06-brutalist-anti-grid": dict(focus="raw but present: high-contrast outline that ignores the broken grid", motion_risk="chaotic entrances rotating from random angles — jarring without a reduced-motion off-switch", a11y_trap="overlapping rotated elements covering text; rotated body text below 4.5:1; screen readers read DOM order not visual order — keep DOM order logical", font_why="raw system/mono fonts (Space Mono, IBM Plex Mono) — the anti-design stance includes refusing polished webfonts", radius_why="0 everywhere — radius is polish, and polish is what this style refuses", density_why="uneven on purpose: dense collage next to vast emptiness — the contrast is the composition", break_rules="break the anti-grid: ONE aligned, ordered section gives the chaos meaning — total disorder is unreadable, curated disorder is design"),
 "07-neumorphism": dict(focus="critical: soft-shadow surfaces swallow focus rings — use strong 3px accent color rings, test on a real keyboard", motion_risk="pressing animations with deep dual shadows — subtle 2-4px travel is enough, more looks like melting", a11y_trap="THE structural flaw: same-color surfaces mean borders and states have almost no contrast — WCAG 1.4.11 (3:1 non-text) is usually impossible without adding outlines; use only for decorative surfaces, never critical controls", font_why="soft rounded sans matches the extruded material; condensed or display faces make soft UI look inflated", radius_why="large radii (16-24px) are required — soft shadows only read as extrusion on curved surfaces", density_why="low-to-medium only: every element pays a legibility tax; dense neumorphic dashboards are unusable", break_rules="add ONE flat, high-contrast control color (a real button) — pure monochrome neumorphism fails; hybrid soft-plus-solid works"),
 "08-claymorphism": dict(focus="chunky visible outlines in a darker clay tone — pastel-on-pastel hides default focus", motion_risk="perpetual squish/bounce idle animations — clay should deform ON interaction, not breathe continuously", a11y_trap="white text on pastel puffs; playful style still needs 4.5:1 — darken the clay or the text", font_why="rounded display sans (Baloo, Nunito) IS the material in type form; sharp grotesks break the soft universe", radius_why="generous (20-32px) with puffy dual shadows — the radius carries the clay metaphor", density_why="low: big puffy elements need air; cramming clay components reads as a toy chest, not a product", break_rules="one sharp, flat element (a serious data table, a legal line) grounds the playfulness — all-clay pages feel unserious beyond kids' products"),
 "09-skeuomorphism-tactile": dict(focus="physical controls already have affordance — add invisible-until-focus rings for keyboard users", motion_risk="dials and levers animating on page load — controls should move only when operated", a11y_trap="real-world mimicry without semantics: a volume knob must still be a range input with aria — looks are decoration, roles are real", font_why="era-appropriate faces (serif for vintage audio, industrial sans for hardware) — the material tells you the family", radius_why="material-driven: brushed metal = small radius, wood/plastic = larger; inconsistency between materials is fine, within one material it is not", density_why="controls need physical size — touch-sized knobs and switches cap density; this is an instrument panel, not a spreadsheet", break_rules="let data display go flat/digital (LCD-style) inside the tactile frame — pure physical everything gets exhausting; contrast makes tactility pop"),
 "10-swiss-international": dict(focus="strict 2px black outline, offset to the grid — focus is part of the system", motion_risk="this style barely animates — if you are adding parallax you have left Swiss; fades of 200ms max", a11y_trap="red accent on gray text; also justified text creating rivers — keep text ragged-right unless hyphenation is managed", font_why="neo-grotesks (Helvetica family, Inter, Archivo) are the style — typography IS the design; a serif display would be a different style", radius_why="0 radius: the grid and the rectangle are sacred — rounding corners softens the rigor into generic modern UI", density_why="structured medium-high density: whitespace is planned, not generous — every gap sits on the grid", break_rules="break the grid only as an accent (one rotated element, one photo bleeding off-grid) — Swiss with one rupture is the master move"),
 "11-editorial-magazine": dict(focus="elegant but visible: a 2px serif-weighted underline or outline that fits the typography", motion_risk="smooth-scroll hijacking for a 'reading experience' — reading flow belongs to the reader, never animate their scroll", a11y_trap="light gray serif body text at 15px — long-form needs 17px+, #333 minimum, 65-75ch measure", font_why="serif display (Fraunces, Playfair) + readable text pairing — the pairing carries literary authority; two sans-serifs is not editorial", radius_why="0-2px: print has no radius; images are sharp rectangles like magazine plates", density_why="high text density with dramatic whitespace alternation — dense column next to full-page image is the magazine rhythm", break_rules="contemporary editorials mix in one grotesk element (labels, data) — pure serif-only pages feel costume-like; the mix IS modern editorial"),
 "12-maximalism": dict(focus="thick, high-contrast outlines that survive background chaos — focus must be findable in noise", motion_risk="everything animating always — in maximalism ONE animated element reads stronger than ten; motion needs a spotlight, not a rave", a11y_trap="patterned backgrounds behind text — always put text on solid plates; busy-on-busy fails every contrast rule", font_why="expressive display families (Unbounded, Archivo Expanded) + a disciplined text face — maximalism needs ONE calm voice amid the noise", radius_why="intentionally mixed per layer (this is the exception to consistency) — but within one component, stay consistent", density_why="high is the point, but layers need hierarchy: background pattern, then mid decoration, then sharp foreground content", break_rules="one zone of extreme minimalism (a plain white section) makes the maximalist rest hit harder — contrast is the real system"),
 "13-y2k-retrofuturism": dict(focus="chrome and iridescence swallow thin focus rings — bold dark outlines or inverted pills required", motion_risk="looping shimmer/glow on everything — loop ONE hero element; shimmer fatigue is instant", a11y_trap="silver/chrome text on light backgrounds, white on iridescent gradients — chrome needs a dark backing plate to pass contrast", font_why="bubble/techno display (Orbitron-like, ultra-rounded) — Y2K type is nostalgic hardware UI; neutral grotesks kill the era", radius_why="extreme pills and bubbles (999px) plus blob shapes — Y2K never met a corner it liked", density_why="medium-high visual density with metallic shine stacking — but interactive content stays on solid 'screen' areas", break_rules="one flat, modern, quiet section makes the retro zones read as intentional art direction instead of a costume"),
 "14-3d-spatial-ui": dict(focus="2D focus rings on top of the 3D layer; 3D-transformed controls must keep standard focus behavior", motion_risk="parallax responding to every mouse move — respect reduced-motion with a static 2D layout fallback", a11y_trap="text on tilted/rotated 3D planes (effective size and contrast change with angle) — keep text on flat layers, 3D for objects", font_why="geometric sans with wide weights (Space Grotesk) matches dimensional space; thin fonts break up at small 3D scales", radius_why="depth-driven: layer radii increase toward the viewer (8/12/16px) — the radius becomes a depth cue", density_why="low-mid: each 3D layer costs attention; spatial UI shows FEW things in MORE space", break_rules="a fully flat 2D section after a 3D journey gives the eyes rest and makes the 3D meaningful — alternate dimensions deliberately"),
 "15-expressive-kinetic-typography": dict(focus="animated type must freeze to a readable static state under reduced-motion — no exceptions", motion_risk="THE core risk: continuous marquee/morph makes text unreadable and vestibular-hazardous — cap continuous animation to one element", a11y_trap="animated or distorted display text carrying critical information (prices, CTAs) — kinetic text is the emotional layer; always duplicate critical info statically", font_why="variable/expressive families (Fraunces with animated axes, Archivo Expanded) — the font's range IS the motion vocabulary", radius_why="driven by the letterforms, not a token — buttons/cards inherit shape language from the type (sharp type, sharp UI)", density_why="type-dense but element-light: one screen, few words, huge scale — density lives INSIDE typography, not in layout", break_rules="pair one dead-plain utility section (normal sans, normal size) — total kinetic saturation exhausts in 10 seconds; contrast keeps motion special"),
}

for path in sorted(glob.glob("/home/aibot/repos/agent-design-taste/styles/*/README.md")):
    name = os.path.basename(os.path.dirname(path))
    if name not in VARIANTS:
        print("MISS", name); continue
    text = open(path, encoding="utf-8").read()
    if "Accessibility Notes" in text:
        print("skip", name); continue
    with open(path, "a", encoding="utf-8") as f:
        f.write(BLOCK.format(**VARIANTS[name]))
    print("ok", name)